objects/A_L_Exception__c.object
<CustomObject>
	<description>To capture Arch&amp;Launch Svc Exception Status.</description>
	<fields>
		<fullName>A_L_Package__c</fullName>
		<label>A&amp;L Package</label>
		<picklist>
			<picklistValues>
				<fullName>AUDIENCE MANAGER</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>AEM</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>CAMPAIGN</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>MULTI-SOLUTION</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>ANALYTICS</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>TARGET</fullName>
			</picklistValues>
		</picklist>
		<required>true</required>
		<type>Picklist</type>
	</fields>
	<fields>
		<fullName>Opportunity__c</fullName>
		<label>Opportunity</label>
		<referenceTo>Opportunity</referenceTo>
		<relationshipName>Arch_Launch_Svc_Exceptions</relationshipName>
		<relationshipOrder>0</relationshipOrder>
		<type>MasterDetail</type>
	</fields>
	<fields>
		<fullName>Status__c</fullName>
		<label>Status</label>
		<picklist>
			<picklistValues>
				<fullName>Exception Requested</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Exception Approved</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Exception Denied</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Adjustment Approved</fullName>
			</picklistValues>
		</picklist>
		<required>true</required>
		<type>Picklist</type>
	</fields>
	<label>A&amp;L Exception</label>
	<nameField>
		<displayFormat>AL-{0000000}</displayFormat>
		<label>A&amp;L Exception #</label>
		<type>AutoNumber</type>
	</nameField>
	<pluralLabel>A&amp;L Exceptions</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Account.object
<CustomObject>
	<fields>
		<fullName>Status__c</fullName>
		<inlineHelpText>The value for this field is system-assigned and therefore read-only.</inlineHelpText>
		<label>Status</label>
		<picklist>
			<picklistValues>
				<fullName>Partially Saved</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Submitted In Review</fullName>
				<default>true</default>
			</picklistValues>
			<picklistValues>
				<fullName>Payment Requested</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Approved</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Denied</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Warning</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Suspended</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Abandoned</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Terminated</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Pending</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Marketing Approved</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Expired</fullName>
			</picklistValues>
			<picklistValues>
				<fullName>Need More Information</fullName>
			</picklistValues>
		</picklist>
		<type>Picklist</type>
	</fields>
</CustomObject>

classes/A_L_ExceptionHandler_Test.cls
/**
* Company     : Adobe Systems Inc.
* Description : Test class to validate the functionality of the AdobeGlobalServiceHandler.
* History     : 
*  Refer GIT for history
*/
@isTest
private class A_L_ExceptionHandler_Test {
	@testSetup
    static void  createTestdata() { 
        CommonTestDataFactory.deActivateTriggerHandlers(new Set<String>{
            'OpportunityLineItemHandler',
            'OpportunityHandler',
            'AccountHandler',
            'AdobeSalesTeamHandler'
        });
        ISO_Country_Code__c oIsoCont = UnitTestHelper.getISOCountryCodeInstance();
        insert oIsoCont;
        
        Map<String, Id> mapOpportunityRecordTypesId = new Map<String, Id>();
        for(RecordType rt : [Select Id, Name, SObjectType from RecordType where SobjectType = 'Opportunity' AND name = 'Adobe Internal Opportunity' order by name asc]) {
            mapOpportunityRecordTypesId.put(rt.Name, Rt.Id);
        }
        
        ID stdPriceBookID = Test.getStandardPricebookId();
        
        //Create Mock Account
        Account objAct = UnitTestHelper.getAccountInstance();
        insert objAct;

        //Create Mock Opportunity
        Opportunity objOpp1 = UnitTestHelper.getOpportunityInstance(objAct.id);
        objOpp1.RecordTypeId = mapOpportunityRecordTypesId.get('Adobe Internal Opportunity');
        objOpp1.Pricebook2Id= stdPriceBookID ;
        objOpp1.StageName = '02 - Prospect';
        insert objOpp1; 
        
        //Create Adobe Sales Team
        Adobe_Sales_Team__c ast1 = new Adobe_Sales_Team__c();
        ast1.Adobe_Territory_Member__c = UnitTestHelper.getATMInsatnces(1, new List<User> {UnitTestHelper.getUserInstance()}, new List<Account> {objAct}).get(0).Id;
        ast1.Sales_Team_Member__c = userInfo.getUserId();
        ast1.Opportunity__c = objOpp1.Id;
        insert ast1;

        //Create Mock A_L_Exception record        
        A_L_Exception__c alexp1 = new A_L_Exception__c();
        alexp1.Opportunity__c = objOpp1.Id;
        alexp1.A_L_Package__c = 'AEM';
        alexp1.Status__c = 'Exception Requested';
        insert alexp1;
        
    }
	@isTest static void testALApprovalMail() {
		List<A_L_Exception__c> listALExcp = [select Id from A_L_Exception__c];
		listALExcp.get(0).Status__c = 'Exception Approved';
		update listALExcp;
	}
	
}